name: nutrisee
description: A new Flutter project.
publish_to: none
version: "1.0.0+1"
environment:
  sdk: ">=2.19.0 <3.0.0"
dependencies:
  bloc_concurrency: ^0.2.0
  camera: ^0.11.0+1
  cloud_firestore: ^5.0.1
  copy_with_extension: ^5.0.4
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.3+1
  dropdown_button2: ^2.3.9
  equatable: ^2.0.3
  event_bus: ^2.0.0
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_storage: ^12.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_gemini: ^2.0.4
  flutter_image_compress: ^2.3.0
  flutter_launcher_icons: ^0.14.1
  flutter_local_notifications: ^17.1.2
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  flutter_tts: ^4.0.2
  gap: ^3.0.1
  get_it: ^7.2.0
  go_router: ^14.1.4
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.6
  gradient_borders: ^1.0.0
  im_stepper: ^1.0.1+1
  image_picker: ^1.0.4
  injectable: ^2.3.0
  intl: ^0.19.0
  ionicons: ^0.2.2
  json_annotation: ^4.8.1
  path: ^1.9.0
  path_provider: ^2.0.11
  permission_handler: ^11.3.1
  retrofit: ^4.1.0
  rxdart: ^0.27.5
  uuid: ^4.0.0
  vibration: ^1.9.0
dev_dependencies:
  build_runner: null
  copy_with_extension_gen: ^5.0.4
  flutter_gen_runner: null
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: null
  json_serializable: null
  retrofit_generator: null
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/maps/

flutter_launcher_icons:
  image_path_android: "assets/images/ic_launcher.png"
  image_path_ios: "assets/images/ic_launcher.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/images/ic_launcher_background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/ic_launcher.png" # only available for Android 8.0 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#FFFFFF"
