// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdNJEHd3JC_SGU7bolTue8-ToEAdxXGeM',
    appId: '1:216665541926:android:8697067ded325f617bc5e7',
    messagingSenderId: '216665541926',
    projectId: 'ocr-flutter-d232e',
    storageBucket: 'ocr-flutter-d232e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN1G1W0OOiaA9uf0EGtciCkH0piDDMdco',
    appId: '1:992837808581:ios:9812762ff1a622bb039bac',
    messagingSenderId: '992837808581',
    projectId: 'nutrisee',
    storageBucket: 'nutrisee.appspot.com',
    iosBundleId: 'com.example.nutrisee',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFqHyGm8K27U-eeeUU_Yy0fce5d56x3CI',
    appId: '1:216665541926:web:df69ca3ebf1098b67bc5e7',
    messagingSenderId: '216665541926',
    projectId: 'ocr-flutter-d232e',
    authDomain: 'ocr-flutter-d232e.firebaseapp.com',
    storageBucket: 'ocr-flutter-d232e.appspot.com',
  );

}